title: iOS 越狱手册
description: >-
  我的 iOS 越狱 (Jailbreak) 教程与文档库：设备、越狱工具（Dopamine / RELAXIN）、插件 (Tweaks) 与玩法记录。
remote_theme: just-the-docs/just-the-docs
lang: zh-CN

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

# just-the-docs
search_enabled: true
heading_anchors: true
